spring:
  application:
    name: spring-boot-log4j2







## tomcat日志打印
server:
  tomcat:
    accesslog:
      enabled: true
      pattern: "%t %a %r %s (%D ms)"
    basedir: ./data/accesslogs/${spring.application.name}
  port: 8080
